sudo: required
services:
    - docker

before_install:
    - docker build -f ./client/Dockerfile.dev -t amitavak/react-test ./client

script:
    - docker run -e CI=true amitavak/react-test npm test

after_success:
    - docker build -t amitavak/multi-client ./client
    - docker build -t amitavak/multi-server ./server
    - docker build -t amitavak/multi-nginx ./nginx
    - docker build -t amitavak/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push amitavak/multi-client
    - docker push amitavak/multi-server
    - docker push amitavak/multi-nginx
    - docker push amitavak/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-Dev
    bucket_name: elasticbeanstalk-ap-south-1-609591418103
    bucket_path: docker_multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY